### ISSUE TITLE
如果可以的话做个网站

### ISSUE THREAD

**Issue by darionyaphet** [gaoxuesong/learning-spark-lightning-fast-big-data-analysis#1]
如果可以的话做个网站  搭建在github  page上面
例如 :  www.XXX.io 啥的 便于大家学习&使用

**Comment by gaoxuesong** [comment]
本来在GitBook上公开，现在看来无法将其公开了，看出版社的警告（ http://weibo.com/1639621773/CetovrBtK?from=page_1005051639621773_profile&wvr=6&mod=weibotime&type=comment ），中文版权已属图灵出版社。

**Comment by wanghaisheng** [comment]
难道朋友之间的分享也是侵权的么

**Comment by darionyaphet** [comment]
原来如此……
